import numpy as np
import random


class ReplayBuffer:
    def __init__(self, capacity, batch_size, unroll_steps, discount, td_steps=5):     
        self.capacity = capacity
        self.batch_size = batch_size
        self.unroll_steps = unroll_steps
        self.gamma = discount
        self.td_steps = td_steps

        self.buffer = []
        self.position = 0

    def save_game(self, game_history):
        """
        Save a completed episode to the replay buffer.

        Each game_history contains:
            - obs
            - actions
            - rewards
            - policies
            - values

        The stored MCTS values are used as bootstrap values when
        building n-step value targets in sample_batch().
        """
        if len(self.buffer) < self.capacity:
            self.buffer.append(None)

        self.buffer[self.position] = game_history
        self.position = (self.position + 1) % self.capacity

    def sample_batch(self):
        """
        Sample a batch of games and construct MuZero training targets.

        Value target (n-step bootstrapped, n = td_steps):
            G_t = r_t + gamma*r_{t+1} + ... + gamma^(n-1)*r_{t+n-1}
                  + gamma^n * V_{t+n}

        V_{t+n} is the stored MCTS value at that step. No bootstrap
        term is added when t+n falls beyond the end of the episode.
        """
        if len(self.buffer) == 0:
            raise ValueError("Cannot sample from an empty replay buffer.")

        if len(self.buffer) < self.batch_size:
            games = random.choices(self.buffer, k=self.batch_size)
        else:
            games = random.sample(self.buffer, self.batch_size)

        obs_batch = []
        act_batch = []
        target_val_batch = []
        target_rew_batch = []
        target_pol_batch = []

        for game in games:
            game_len = len(game["actions"])

            if game_len < self.unroll_steps:
                raise ValueError(
                    f"Game is too short for unroll_steps={self.unroll_steps}: "
                    f"game_len={game_len}"
                )

            # Leave enough room for a complete unroll.
            max_start = game_len - self.unroll_steps
            start_index = random.randint(0, max_start)

            obs_batch.append(game["obs"][start_index])

            actions = game["actions"][
                start_index:start_index + self.unroll_steps
            ]
            act_batch.append(actions)

            val_seq = []
            rew_seq = []
            pol_seq = []

            for k in range(self.unroll_steps):
                current_idx = start_index + k

                # n-step bootstrapped return from current_idx:
                # r_t + g*r_{t+1} + ... + g^(n-1)*r_{t+n-1} + g^n * V_{t+n}
                value_target = 0.0

                end_idx = min(current_idx + self.td_steps, game_len)

                for i in range(current_idx, end_idx):
                    value_target += (
                        self.gamma ** (i - current_idx)
                    ) * float(game["rewards"][i])

                bootstrap_idx = current_idx + self.td_steps
                if bootstrap_idx < game_len:
                    value_target += (
                        self.gamma ** self.td_steps
                    ) * float(game["values"][bootstrap_idx])

                val_seq.append(float(value_target))

                # Reward produced by the corresponding environment action.
                rew_seq.append(float(game["rewards"][current_idx]))

                # Policy generated by MCTS at this state.
                policy = np.asarray(
                    game["policies"][current_idx],
                    dtype=np.float32,
                )

                policy_sum = float(policy.sum())

                if (
                    policy.ndim != 1
                    or len(policy) == 0
                    or not np.all(np.isfinite(policy))
                    or policy_sum <= 0.0
                ):
                    raise ValueError(
                        f"Invalid policy at index {current_idx}: {policy}"
                    )

                policy = policy / policy_sum
                pol_seq.append(policy.tolist())

            target_val_batch.append(val_seq)
            target_rew_batch.append(rew_seq)
            target_pol_batch.append(pol_seq)

        return {
            "observations": obs_batch,
            "actions": act_batch,
            "target_values": target_val_batch,
            "target_rewards": target_rew_batch,
            "target_policies": target_pol_batch,
        }

    def size(self):
        """Return the number of stored games."""
        return len(self.buffer)